### ISSUE TITLE
Argument 1 passed to Illuminate\Auth\SessionGuard::login()

### ISSUE THREAD

**Issue by Ngizeh** [spatie/dashboard.spatie.be#124]

**Comment by freekmurze** [comment]
There’s no information enough for us to go on.

**Comment by Ngizeh** [comment]
On cloning the repo I am getting this

In SessionGuard.php line 407:
                                                                               
  Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement i  
  nterface Illuminate\Contracts\Auth\Authenticatable, null given, called in /  
  /dashboard.spatie.be/vendor/laravel/framework/src/Illum  
  inate/Auth/AuthManager.php on line 292

**Comment by luchaos** [comment]
It's because of this line in the `AuthServiveProvider`which gets called regardless of there being a migrated database/user to be found: https://github.com/spatie/dashboard.spatie.be/blob/master/app/Providers/AuthServiceProvider.php#L25
The call is also the reason for `artisan package:discover` to fail after the initial installation, when there is no `database/database.sqlite` file yet.

Solution:

Commenting that mentioned line above, then running...
`cp .env.example .env` (+ add `ACCESS_TOKEN` value to `.env`)
`composer install && yarn install && yarn run dev`
`touch database/database.sqlite`
`php artisan migrate`
`php artisan db:seed` (change values in `https://github.com/spatie/dashboard.spatie.be/blob/master/database/seeds/DatabaseSeeder.php` first, add User model use statement)
... then uncommenting the line again works nicely (i.e. https://dashboard.test/?access-token=ACCESS_TOKEN).

As mentioned in the article the Auth should be changed to one's needs. The above is just to make it run out of the box.
