### ISSUE TITLE
Uptime tile doesn't seem to be working

### ISSUE THREAD

**Issue by freekmurze** [spatie/dashboard.spatie.be#80]

**Comment by etiennemarais** [comment]
Might it be related to the [recent upgrade of laravel echo](https://github.com/laravel/echo/commit/fdaa4c4f708290f7a6947b61bc63bf51fab59bd5) that seems to have switched up the naming of broadcast events? 

I updated my `/mixins/echo.js` to:

```
...
.listen('.App\\Events\\' + eventName, response => handler(response));
```

and the actual component vue component:

```
methods: {
        getEventHandlers() {
            return {
                'Tasks\\TasksFetched': response => {
                    console.log(response.tasks[this.teamMember]);
                    this.tasks = response.tasks[this.teamMember];
                },
            };
        },
```

This seems to have solved it because the event name in the pusher call was getting fired fine and comping into the app also fine. The listen seemed to have borked.

**Comment by freekmurze** [comment]
Thanks for the hinkt, I'll check this out soon.
