### ISSUE TITLE
No testing for application?

### ISSUE THREAD

**Issue by mehrdaad** [spatie/dashboard.spatie.be#81]
I tried to get some inspiration from how you test a Laravel application, but I found tests directory is empty(!)  
Why didn't you add test for this app?  
Also is there any repo you can point me to, to get some inspiration on Laravel application testing?

**Comment by freekmurze** [comment]
We didn't add tests for the Laravel code here, because the code itself is kinda boring. The real bulk of the server side work happens in the packages the dashboard is using and they have their own tests. 

If there's something wrong with the application itself we notice it immediately on our own dashboard, so the value tests bring to the table are lower than in a typical project. 

But sure, we could add some just to be sure, when we have some time.
